### PR TITLE
Added Searching Algorithms (in C++)

### PR DESCRIPTION
**Pull request by swoyam2609**
Issue no. #16 
Uploaded the codes of some of the famous Searching Algorithms in C++, these include:

- Linear Search Algorithm
- Iterative approach of Binary Search Algorithm
- Recursive approach of Binary Search Algorithm
- Jump Search Algorithm
- Interpolation Search Algorithm

### CODE REVIEW

**Comment by tomriddle77** [comment]
Please goto issue section create a issue there or find a related issue and come back here and then tag that issue so that I can assign it to you and merge it.

**Comment by swoyam2609** [comment]
Issue #16 
As requested, I have opened an Issue and tagged the same. Please do the required

With Regards,
Swoyam Siddharth Nayak

**Comment by tomriddle77** [comment]
Now you have made a valid Contribution but I suggest you to please add a single code next time.

**Review by tomriddle77 — APPROVED** [review]
Please add a single code next time or you can do the same this time

**Comment by swoyam2609** [comment]
> Now you have made a valid Contribution but I suggest you to please add a single code next time.

Sorry, Actually coudn't understand, did you mean that I should upload the complete code in a single file ??

**Pull request merged**
