### PR TITLE
Create binary-search.cpp

### PR DESCRIPTION
**Pull request by shreyashchavan**
Useful algorithm. Most questions, ask in interviews are from this age.

NAME : Shreyash Chavan
GITHUB : [@shreyashchavan](https://github.com/shreyashchavan)
INSTITUTE/COMPANY : Student, SITCOE
DOMAIN/LANGUGAE : C++, C, Python

### CODE REVIEW

**Comment by tomriddle77** [comment]
Please add some valid code Simple binary search is not valid and please tag the issue here

**Comment by shreyashchavan** [comment]
why not valid?

**Comment by tomriddle77** [comment]
Someone already added few searching algos' to this repository so I request you to make a valid contribution

**Comment by tomriddle77** [comment]
If you  will add some other code for example finding peak element using binary search or something else then I will accept it.

**Comment by shreyashchavan** [comment]
sorry to say but, at the time I make PR there is no folder of that.

**Comment by tomriddle77** [comment]
> sorry to say but, at the time I make PR there is no folder of that.

thats why I humbly request you to please make another PR

**Pull request closed without merging**
