### PR TITLE
Create TicTacToe.py

### PR DESCRIPTION
**Pull request by driftmaniacc**

### CODE REVIEW

**Review by tomriddle77 — COMMENTED** [review]
please add it to python folder

**Comment by driftmaniacc** [comment]
I added it the python folder only and I checked it once again.Please tell me the issue and I will try to fix it

**Review by tomriddle77 — APPROVED** [review]
Okay you have made a valid contribution.

**Comment by tomriddle77** [comment]
though this was not a beginner friendly code but still I am accepting it so that you can get your first PR

**Pull request merged**
